"""
models/analyze.py — Pydantic schemas for POST /analyze.
"""

from pydantic import BaseModel, Field


class AnalyzeRequest(BaseModel):
    subject: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Subject name, e.g. 'Quantum Mechanics' or 'World War II'",
    )
    content: str = Field(
        ...,
        min_length=50,
        max_length=500_000,
        description="Student notes as plain text (50–500 000 characters)",
    )


class ConceptScore(BaseModel):
    concept: str = Field(..., description="Concept name generated by the LLM")
    score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Cosine similarity between notes and concept (0 = no coverage, 1 = full coverage)",
    )


class AnalyzeResponse(BaseModel):
    subject: str
    concepts: list[ConceptScore] = Field(
        ...,
        description="Scored list of 15 concepts relevant to the subject",
    )
